[package]
name = "sanscript_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum_macros = "0.25"
serde = { version = "1.0.198", features = ["derive"] }
rand = "0.9.0-alpha.1"